.TH "include/LCDMenu.h" 3 "Wed Dec 21 2016" "PROS LCD Menu Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/LCDMenu.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBLCDMenu\fP"
.br
.RI "this hold all the variables needed for a \fBLCDMenu\fP or sub menu\&. "
.ti -1c
.RI "struct \fBLCDItem\fP"
.br
.RI "holds the information for individual items, mainly the text to be displayed\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBselectChooseType\fP \fBselectChooseType\fP"
.br
.RI "each menu and sub-menu can be configured to use different types of input for item selection and choice\&. "
.ti -1c
.RI "typedef enum \fBitemType\fP \fBitemType\fP"
.br
.ti -1c
.RI "typedef struct \fBLCDItem\fP \fBLCDItem\fP"
.br
.ti -1c
.RI "typedef struct \fBLCDMenu\fP \fBLCDMenu\fP"
.br
.RI "this hold all the variables needed for a \fBLCDMenu\fP or sub menu\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBselectChooseType\fP { \fBPOTENTIOMETER\fP, \fBDIGITAL_SENSOR\fP, \fBLCD_BUTTONS\fP }
.RI "each menu and sub-menu can be configured to use different types of input for item selection and choice\&. ""
.br
.ti -1c
.RI "enum \fBitemType\fP { \fBFUNCTION_EXEC\fP, \fBSUB_MENU\fP, \fBSELECTION_ONLY\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLCDMenuTask\fP (void *ignore)"
.br
.RI "this should be started as a task in initialize\&. "
.ti -1c
.RI "void \fBnewItem\fP (char *itemText, void(*itemFunction)())"
.br
.RI "adds an item to the menu "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBLCDItem\fP * \fBLCDMenuItems\fP"
.br
.ti -1c
.RI "int \fBcurrentSelection\fP"
.br
.ti -1c
.RI "sensor \fBselectionPot\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef enum \fBitemType\fP \fBitemType\fP"
this enum show if an item can be choosen, and if it can wether or not it's a sub menu or if it executes a function\&.
.PP
\fBSee also:\fP
.RS 4
\fBLCDMenu\fP 
.RE
.PP

.SS "typedef struct \fBLCDItem\fP \fBLCDItem\fP"

.PP
\fBSee also:\fP
.RS 4
forward declaration/typedef of \fBLCDItem\fP struct 
.RE
.PP

.SS "typedef struct \fBLCDMenu\fP \fBLCDMenu\fP"

.PP
this hold all the variables needed for a \fBLCDMenu\fP or sub menu\&. 
.SS "typedef enum \fBselectChooseType\fP \fBselectChooseType\fP"

.PP
each menu and sub-menu can be configured to use different types of input for item selection and choice\&. 
.PP
\fBNote:\fP
.RS 4
when an item is chosen, it's selected and it's function is executed or it's sub-menu displayed (see itemType) and is selected when \fBLCDMenu\&.currentSelection\fP is at the item's array index (\fBLCDMenu\&.LCDItems\fP) 
.RE
.PP

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBitemType\fP"
this enum show if an item can be choosen, and if it can wether or not it's a sub menu or if it executes a function\&.
.PP
\fBSee also:\fP
.RS 4
\fBLCDMenu\fP 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFUNCTION_EXEC \fP\fP
exacute the function that \fBLCDItem\&.function\fP points to when this item is chosen\&.
.PP
\fBSee also:\fP
.RS 4
LCDMenu\&.function 
.RE
.PP

.TP
\fB\fISUB_MENU \fP\fP
if \fBLCDItem\&.itemType\fP is set to this it means that there's a sub menu in \fBLCDItem\&.subMenu\fP\&.
.PP
\fBSee also:\fP
.RS 4
\fBLCDItem\&.subMenu\fP 
.RE
.PP

.TP
\fB\fISELECTION_ONLY \fP\fP
this means that the item is not a subMenu and does not have a function in the function pointer and thus cannot be chosen\&. 
.SS "enum \fBselectChooseType\fP"

.PP
each menu and sub-menu can be configured to use different types of input for item selection and choice\&. 
.PP
\fBNote:\fP
.RS 4
when an item is chosen, it's selected and it's function is executed or it's sub-menu displayed (see itemType) and is selected when \fBLCDMenu\&.currentSelection\fP is at the item's array index (\fBLCDMenu\&.LCDItems\fP) 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPOTENTIOMETER \fP\fP
use a potentiometer to select and/or choose an item the advantage of this being that the selection will be the same after the robot is turned off, making it useful for autonomous selection
.PP
\fBNote:\fP
.RS 4
should not be used choose sub menus\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBLCDMenu\&.selectionType\fP 
.PP
\fBLCDMenu\&.chooseType\fP 
.RE
.PP

.TP
\fB\fIDIGITAL_SENSOR \fP\fP
use a/some digital sensor(s) (probally bumber switches) to select and or choose items\&. 
.TP
\fB\fILCD_BUTTONS \fP\fP
use the items built into the LCD\&. 
.SH "Function Documentation"
.PP 
.SS "void LCDMenuTask (void * ignore)"

.PP
this should be started as a task in initialize\&. 
.SS "void newItem (char * itemText, void(*)() itemFunction)"

.PP
adds an item to the menu 
.SH "Variable Documentation"
.PP 
.SS "int currentSelection"

.SS "\fBLCDItem\fP* LCDMenuItems"

.SS "sensor selectionPot"

.SH "Author"
.PP 
Generated automatically by Doxygen for PROS LCD Menu Library from the source code\&.
