.TH "src/LCDMenu.c" 3 "Wed Dec 21 2016" "PROS LCD Menu Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/LCDMenu.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include 'LCDMenuSettings\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLCDMenuTask\fP (void *ignore)"
.br
.RI "this should be started as a task in initialize\&. "
.ti -1c
.RI "void \fBnewItem\fP (char *itemText, void(*itemFunction)())"
.br
.RI "adds an item to the menu "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "size_t \fBnumOfItems\fP = 0"
.br
.ti -1c
.RI "\fBLCDItem\fP * \fBLCDMenuItems\fP = NULL"
.br
.ti -1c
.RI "int \fBcurrentSelection\fP"
.br
.ti -1c
.RI "int \fBpotSelectionSize\fP"
.br
.ti -1c
.RI "int \fBselectionRangeUpper\fP"
.br
.ti -1c
.RI "int \fBselectionRangeLower\fP"
.br
.ti -1c
.RI "sensor \fBselectionPot\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void LCDMenuTask (void * ignore)"

.PP
this should be started as a task in initialize\&. 
.SS "void newItem (char * itemText, void(*)() itemFunction)"

.PP
adds an item to the menu 
.SH "Variable Documentation"
.PP 
.SS "int currentSelection"

.SS "\fBLCDItem\fP* LCDMenuItems = NULL"

.SS "size_t numOfItems = 0"

.SS "int potSelectionSize"

.SS "sensor selectionPot"

.SS "int selectionRangeLower"

.SS "int selectionRangeUpper"

.SH "Author"
.PP 
Generated automatically by Doxygen for PROS LCD Menu Library from the source code\&.
