.TH "include/LCDMenuSettings.h" 3 "Wed Dec 21 2016" "PROS LCD Menu Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/LCDMenuSettings.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLCD_POINTER_CHAR\fP   '>'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LCD_POINTER_CHAR   '>'"

.SH "Author"
.PP 
Generated automatically by Doxygen for PROS LCD Menu Library from the source code\&.
